### ISSUE TITLE
Ошибка обработки строки 

### ISSUE THREAD

**Issue by vopvivy** [GyverLibs/AsyncStream#1]
Версия IDE 1.8.19
Пакет данных: $key1+Ctrl;
Скетч: пример из Библиотеки
Результат в мониторе порта: ХРЕНЬ!

**Comment by GyverLibs** [comment]
Разбираемся с настройками монитора
![image](https://user-images.githubusercontent.com/84599917/180095390-62e72eac-9e85-43a0-9dbf-fe724af00f48.png)

**Comment by vopvivy** [comment]
Проблема! После пакета данных нет /n.
В AsyncStream вместо терминатора '/n' стоит ';'
В монитор порта выводятся две строчки пакета: первая строчка без ; в конце, вторая строчка без $ в начале и без ; в конце. Настройки монитора перепробовал все, все тоже самое. Почему так происходит?
