### ISSUE TITLE
Ошибка при обработке строки с другим терминатором

### ISSUE THREAD

**Issue by vopvivy** [GyverLibs/AsyncStream#2]
Проблема в том, что после пакета данных нет /n.
В AsyncStream вместо терминатора '/n' стоит ';'
В монитор порта выводятся две строчки пакета: первая строчка без ; в конце, вторая строчка без $ в начале и без ; в конце. Настройки монитора перепробовал все, все тоже самое. Почему так происходит? И как от этого избавиться?

**Comment by GyverLibs** [comment]
Удалось повторить баг, исправил, выкатил обновление. Спасибо за репорт!
